# heavymetal/migrations/versions/6926966c934c_squashed_baseline_full_schema.py
"""squashed baseline — full schema from the models

Replaces the original 4-migration chain (52d889bcec91 → f269d9444cd2), whose
baseline was an autogenerate against a pre-existing DB and so could not build
from scratch. This single migration creates the entire current schema, so
`flask db upgrade` works on an empty database (verified to reproduce the model
schema exactly). Existing prod/dev DBs were re-stamped to this revision.

Revision ID: 6926966c934c
Revises:
Create Date: 2026-06-25 15:30:08.587870

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6926966c934c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("equipment", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "workout_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("parent_plan_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parent_plan_id"],
            ["workout_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "body_measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("neck", sa.Float(), nullable=True),
        sa.Column("bicep_left", sa.Float(), nullable=True),
        sa.Column("bicep_right", sa.Float(), nullable=True),
        sa.Column("chest", sa.Float(), nullable=True),
        sa.Column("waist_below", sa.Float(), nullable=True),
        sa.Column("waist_navel", sa.Float(), nullable=True),
        sa.Column("waist_above", sa.Float(), nullable=True),
        sa.Column("hips", sa.Float(), nullable=True),
        sa.Column("thigh_left", sa.Float(), nullable=True),
        sa.Column("thigh_right", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint("bicep_left > 0", name="body_measurements_bicep_left_check"),
        sa.CheckConstraint(
            "bicep_right > 0", name="body_measurements_bicep_right_check"
        ),
        sa.CheckConstraint("chest > 0", name="body_measurements_chest_check"),
        sa.CheckConstraint("hips > 0", name="body_measurements_hips_check"),
        sa.CheckConstraint("neck > 0", name="body_measurements_neck_check"),
        sa.CheckConstraint("thigh_left > 0", name="body_measurements_thigh_left_check"),
        sa.CheckConstraint(
            "thigh_right > 0", name="body_measurements_thigh_right_check"
        ),
        sa.CheckConstraint(
            "waist_above > 0", name="body_measurements_waist_above_check"
        ),
        sa.CheckConstraint(
            "waist_below > 0", name="body_measurements_waist_below_check"
        ),
        sa.CheckConstraint(
            "waist_navel > 0", name="body_measurements_waist_navel_check"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "consistency_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("weight_tracked", sa.Boolean(), nullable=True),
        sa.Column("calories_tracked", sa.Boolean(), nullable=True),
        sa.Column("sleep_tracked", sa.Boolean(), nullable=True),
        sa.Column("steps_tracked", sa.Boolean(), nullable=True),
        sa.Column("body_measured", sa.Boolean(), nullable=True),
        sa.Column("goal_met", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("measurement_type", sa.String(length=50), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("confidence_flag", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint("value > 0", name="measurements_value_check"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.create_index(
            "idx_measurements_weight_lbs_date",
            ["measurement_type", "unit", "date"],
            unique=False,
        )

    op.create_table(
        "targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("weight_low", sa.Float(), nullable=False),
        sa.Column("weight_high", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=False),
        sa.Column("sessions_week", sa.Integer(), nullable=False),
        sa.Column("sleep_hours", sa.Float(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "workout_plan_exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column("sets", sa.Integer(), server_default="3", nullable=False),
        sa.Column("reps_min", sa.Integer(), nullable=True),
        sa.Column("reps_max", sa.Integer(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["workout_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "plan_id",
            "exercise_id",
            name="workout_plan_exercises_plan_id_exercise_id_key",
        ),
    )
    op.create_table(
        "workout_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column(
            "session_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["workout_plans.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workout_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["workout_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id",
            "exercise_id",
            "set_number",
            name="workout_sets_session_id_exercise_id_set_number_key",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_sets")
    op.drop_table("workout_sessions")
    op.drop_table("workout_plan_exercises")
    op.drop_table("targets")
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.drop_index("idx_measurements_weight_lbs_date")

    op.drop_table("measurements")
    op.drop_table("consistency_logs")
    op.drop_table("body_measurements")
    op.drop_table("workout_plans")
    op.drop_table("users")
    op.drop_table("exercises")
    # ### end Alembic commands ###
